#!/bin/bash 
#  *
#  *                       cloudFPGA
#  *     Copyright IBM Research, All Rights Reserved
#  *    =============================================
#  *     Created: Dec 2019
#  *     Authors: FAB, WEI, NGL
#  *
#  *     Description:
#  *       Script for starting ZRLMPI run
#  *
#  *

# we don't now all folder names, but the levels
../../../cFDK/SRA/LIB/bash/assert_envs.sh || exit 1

source $cFpRootDir/ZRLMPI/py_zrlmpi/bin/activate
python3 ./zrlmpi_run.py "$@"
